services:
 backend:
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
   - "5000:5000"

 frontend:
  build:
   context: ./frontend
   dockerfile: Dockerfile
   args:
    REACT_APP_MOVIE_API_URL: http://localhost:5000
  ports:
   - "3000:3000"
  depends_on:
   - backend
  